[package]
name = "transport-rtpengine"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
num_enum = { workspace = true }
derive_more = { workspace = true, features = ["full"] }
sans-io-runtime = { workspace = true, default-features = false }
media-server-secure = { path = "../media_secure" }
media-server-core = { path = "../media_core" }
media-server-protocol = { path = "../protocol" }
media-server-utils = { path = "../media_utils" }
media-server-codecs = { path = "../media_codecs", default-features = false, features = ["pcma", "opus"] }
sdp-rs = "0.2"
rtp-rs = "0.6"
