[package]
name = "atm0s-media-server-transport-rtpengine"
version = "0.1.0-alpha.2"
authors = ["Giang Minh <giang.ndm@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Transport RtpEngine Component for Atm0s Media Server"

[dependencies]
log = { workspace = true }
num_enum = { workspace = true }
derive_more = { workspace = true, features = ["full"] }
sans-io-runtime = { workspace = true, default-features = false }
media-server-core = { workspace = true }
media-server-protocol = { workspace = true }
media-server-utils = { workspace = true }
media-server-codecs = { workspace = true, default-features = false, features = [
    "pcma",
    "opus",
] }
sdp-rs = { workspace = true }
rtp-rs = { workspace = true }
