[package]
name = "atm0s-media-server-utils"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Utils for atm0s-media-server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
sorted-vec = "0.8"
poem-openapi = { version = "3.0" }
log = { workspace = true }
async-std = { workspace = true }
lz4_flex = { version = "0.11.1" }
flate2 = { version = "1.0.28" }
