[package]
name = "atm0s-media-server-utils"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Utils for atm0s-media-server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
sorted-vec = "0.8"
poem-openapi = { version = "3.0" }
log = { workspace = true }