[package]
name = "transport-rtmp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
endpoint = { workspace = true }
transport = { workspace = true }
async-std = { workspace = true }
async-trait = { workspace = true }
media-utils = { workspace = true }
rml_rtmp = "*"
log = { workspace = true }
futures = { workspace = true }
rtp = "0.9.0"
bytes = "1"
xflv = "0.3.0"
fdk-aac = "0.5.0"
opus = "0.3.0"