[workspace]
git_release_enable = false

[[package]]
name = "atm0s-media-server"
git_release_enable = true
git_release_name = "v{{ version }}"
git_tag_name = "v{{ version }}"
changelog_include = [
    "atm0s-media-server-audio-mixer",
    "atm0s-media-server-cluster",
    "atm0s-media-server-endpoint",
    "atm0s-media-server-utils", 
    "atm0s-media-server-mix-minus", 
    "atm0s-media-server-proc-macro", 
    "atm0s-media-server-protocol", 
    "atm0s-media-server-transport", 
    "atm0s-media-server-transport-webrtc",
    "atm0s-media-server-transport-sip",
    "atm0s-media-server-transport-rtmp",
]