[workspace]
git_release_enable = false

[[package]]
name = "atm0s-media-server"
git_release_enable = true
git_release_name = "v{{ version }}"
git_tag_name = "v{{ version }}"
changelog_include = [
    "atm0s-media-server-audio-mixer",
    "atm0s-media-server-utils",
    "atm0s-media-server-core",
    "atm0s-media-server-runner",
    "atm0s-media-server-protocol",
    "atm0s-media-server-console-front",
    "atm0s-media-server-connector",
    "atm0s-media-server-record",
    "atm0s-media-server-gateway",
    "atm0s-media-server-audio-mixer",
    "atm0s-media-server-secure",
    "atm0s-media-server-codecs",
    "atm0s-media-server-multi-tenancy",
    "atm0s-media-server-transport-webrtc",
    "atm0s-media-server-transport-rtpengine",
]
