[build.env]
passthrough = [
    "RUST_BACKTRACE",
    "RUST_LOG",
    "LIBOPUS_STATIC",
    "LIBSOXR_STATIC",
    "OPENSSL_STATIC",
    "SKIP_BUILD_CONSOLE_FRONT"
]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "apt-get update && apt-get --assume-yes install pkg-config protobuf-compiler libssl-dev"
]
[target.aarch64-unknown-linux-musl]
pre-build = [
    "apt-get update && apt-get --assume-yes install pkg-config protobuf-compiler libssl-dev"
]
