[build.env]
passthrough = [
    "RUST_BACKTRACE",
    "RUST_LOG",
    "LIBOPUS_STATIC",
    "LIBSOXR_STATIC",
    "OPENSSL_STATIC"
]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get --assume-yes install protobuf-compiler libssl-dev:$CROSS_DEB_ARCH"
]
[target.aarch64-unknown-linux-musl]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get --assume-yes install protobuf-compiler libssl-dev:$CROSS_DEB_ARCH"
]
