[package]
name = "media-server-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { workspace = true }
num_enum = { workspace = true }
smallmap = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
sans-io-runtime = { workspace = true, default-features = false }
atm0s-sdn = { workspace = true }
media-server-protocol = { path = "../protocol" }
media-server-utils = { path = "../media_utils" }
