[package]
name = "media-server-protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
convert-enum = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
prost = { workspace = true }
serde = "1.0.200"

[build-dependencies]
prost-build = "0.12"
