[package]
name = "atm0s-media-server-protocol"
version = "0.1.1"
authors = ["Giang Minh <giang.ndm@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Core Protocol Component for Atm0s Media Server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
convert-enum = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true, features = ["full"] }
rand = { workspace = true }
prost = { workspace = true }
serde = { workspace = true, features = ["derive"] }
quinn = { workspace = true, optional = true }
tokio = { workspace = true, features = ["rt"] }

[build-dependencies]
prost-build = { workspace = true }
tera = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[features]
default = []
build-protobuf = []
quinn-rpc = ["quinn"]
