[package]
name = "media-server-protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
log = { workspace = true }
convert-enum = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
prost = { workspace = true }
serde = { version = "1.0.200", features = ["derive"] }
quinn = { version = "0.11", optional = true }
tokio = { version = "1", features = ["rt"] }

[build-dependencies]
prost-build = "0.12"
tera = "1"
serde = { version = "1.0.200", features = ["derive"] }

[features]
default = []
build-protobuf = []
quinn-rpc = ["quinn"]
