[package]
name = "atm0s-media-server-runner"
version = "0.1.0"
authors = ["Giang Minh <giang.ndm@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Media Runner Component for Atm0s Media Server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { workspace = true }
log = { workspace = true }
num_enum = { workspace = true }
convert-enum = { workspace = true }
indexmap = { workspace = true }
media-server-protocol = { workspace = true }
media-server-secure = { workspace = true }
media-server-gateway = { workspace = true }
media-server-connector = { workspace = true }
media-server-core = { workspace = true }

sans-io-runtime = { workspace = true, default-features = false }
atm0s-sdn = { workspace = true }
atm0s-sdn-network = { workspace = true }
transport-webrtc = { workspace = true, optional = true }
transport-rtpengine = { workspace = true, optional = true }

[features]
default = ["webrtc", "rtpengine"]
webrtc = ["transport-webrtc"]
rtpengine = ["transport-rtpengine"]
