[package]
name = "media-server-runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { workspace = true }
media-server-protocol = { path = "../protocol" }
media-server-core = { path = "../media_core" }

sans-io-runtime = { workspace = true, default-features = false }
atm0s-sdn = { workspace = true }
transport-webrtc = { path = "../transport_webrtc", optional = true }

[features]
default = ["webrtc"]
webrtc = ["transport-webrtc"]
