[package]
name = "media-server-runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { workspace = true }
log = { workspace = true }
num_enum = { workspace = true }
convert-enum = { workspace = true }
indexmap = { workspace = true }
media-server-protocol = { path = "../protocol" }
media-server-secure = { path = "../media_secure" }
media-server-gateway = { path = "../media_gateway" }
media-server-connector = { path = "../media_connector" }
media-server-core = { path = "../media_core" }

sans-io-runtime = { workspace = true, default-features = false }
atm0s-sdn = { workspace = true }
atm0s-sdn-network = { workspace = true }
transport-webrtc = { path = "../transport_webrtc", optional = true }
transport-rtpengine = { path = "../transport_rtpengine", optional = true }

[features]
default = ["webrtc", "rtpengine"]
webrtc = ["transport-webrtc"]
rtpengine = ["transport-rtpengine"]
