[package]
name = "atm0s-media-server-transport"
version = "0.1.0"
edition = "2021"
description = "Transport Interface for atm0s-media-server"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
async-std = { workspace = true }
media-utils = { workspace = true }
serde = { workspace = true }
