[package]
name = "atm0s-media-server-transport"
version = "0.2.0"
edition = "2021"
description = "Transport Interface for atm0s-media-server"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
media-utils = { package = "atm0s-media-server-utils", path = "../media-utils", version = "0.2.0" }
async-trait = { workspace = true }
async-std = { workspace = true }
serde = { workspace = true }
poem-openapi = { version = "4.0" }
