[package]
name = "media-server-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smallmap = { workspace = true }
sorted-vec = "0.8"
log = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
uriparse = "0.6.4"
serde-querystring = "0.2.1"
