[package]
name = "media-server-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
embed-files = ["poem", "rust-embed", "hex", "mime_guess"]

[dependencies]
sorted-vec = "0.8"
indexmap = { workspace = true }
log = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
uriparse = "0.6"
serde-querystring = "0.2"
pin-project-lite = "0.2"
spin = { workspace = true }
once_cell = "1.20"
urlencoding = "2.1"
derive_more = { version = "1.0", features = ["full"] }

poem = { version = "3.0", features = [], optional = true }
rust-embed = { version = "8.0", features = ["compression"], optional = true }
hex = { version = "0.4", optional = true }
mime_guess = { version = "2.0", optional = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "map_bench"
harness = false

