[package]
name = "atm0s-media-server-utils"
version = "0.3.0-alpha.1"
authors = ["Giang Minh <giang.ndm@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Media Utils Component for Atm0s Media Server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
embed-files = ["poem", "rust-embed", "hex", "mime_guess"]

[dependencies]
sorted-vec = { workspace = true }
indexmap = { workspace = true }
log = { workspace = true }
serde = { workspace = true, features = ["derive"] }
uriparse = { workspace = true }
serde-querystring = { workspace = true }
pin-project-lite = { workspace = true }
spin = { workspace = true }
once_cell = { workspace = true }
urlencoding = { workspace = true }
derive_more = { workspace = true, features = ["full"] }

poem = { workspace = true, features = [], optional = true }
rust-embed = { workspace = true, features = ["compression"], optional = true }
hex = { workspace = true, optional = true }
mime_guess = { workspace = true, optional = true }

[dev-dependencies]
criterion = { workspace = true, features = ["html_reports"] }

[[bench]]
name = "map_bench"
harness = false
