[package]
name = "media-server-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smallmap = { workspace = true }
sorted-vec = "0.8"
log = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
uriparse = "0.6"
serde-querystring = "0.2"
pin-project-lite = "0.2"
spin = { workspace = true }
once_cell = "1.20"
derive_more = "1.0"
urlencoding = "2.1"