[package]
name = "rtpengine-ngcontrol"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37", features = ["sync", "net"] }
serde = { version = "1.0", features = ["derive"] }
serde_bencode = { version = "0.2.4" }
log = { workspace = true }
