version: '3.8'
services:
  drachtio-server:
    image: drachtio/drachtio-server:0.9.0
    command: drachtio --port 9022 --contact "sip:127.0.0.1:25060;transport=tcp,udp" --contact "sip:127.0.0.1:25080;transport=tcp,udp"
    environment:
      DRACHTIO_SECRET: '123456789'
    network_mode: host
  # freeswitch:
  #   image: drachtio/drachtio-freeswitch-mrf:0.9.0-2
  #   network_mode: host
  #   command: freeswitch --sip-port 5038 --tls-port 5039 --rtp-range-start 50000 --rtp-range-end 55000 --password 123456789
  # rtp-engine:
  #   image: davehorton/rtpengine:latest
  #   network_mode: host
