[package]
name = "media-server-gateway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { workspace = true }
serde = { workspace = true, features = ["derive"] }
media-server-protocol = { path = "../protocol" }
media-server-utils = { path = "../media_utils" }
media-server-secure = { path = "../media_secure", default-features = false }
atm0s-sdn = { workspace = true }
prost = { workspace = true }
spin = { workspace = true }
derive_more = { workspace = true }
tokio = { workspace = true, features = ["time"] }

[dev-dependencies]
httpmock = { workspace = true }