[package]
name = "audio-mixer"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Audio Mixer Component for Atm0s Media Server"

[dependencies]
log.workspace = true
indexmap.workspace = true
