[package]
name = "atm0s-media-server-audio-mixer"
version = "0.1.1"
authors = ["Giang Minh <giang.ndm@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Audio Mixer Component for Atm0s Media Server"

[dependencies]
log.workspace = true
indexmap.workspace = true
