[package]
name = "atm0s-media-server-multi-tenancy"
version = "0.1.0"
authors = ["Giang Minh <giang.ndm@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Multi Tenancy Component for Atm0s Media Server"

[dependencies]
media-server-protocol = { workspace = true }
media-server-secure = { workspace = true, default-features = false }

spin = { workspace = true }
log = { workspace = true }
serde = { workspace = true, features = ["derive"] }
reqwest = { workspace = true, features = ["json"] }
tokio = { workspace = true, features = ["time"] }

[dev-dependencies]
httpmock = { workspace = true }
