[package]
name = "transport-webrtc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
endpoint = { workspace = true }
transport = { workspace = true }
async-std = { workspace = true }
async-trait = { workspace = true }
media-utils = { workspace = true }
poem-openapi = { version = "*", features = ["swagger-ui"] }
str0m = { git = "https://github.com/8xff/str0m.git", rev = "cb88b4b4394a9513e1f5added457f2d724c61421"}
futures = { workspace = true }
log = { workpsace = true }
serde = { workspace = true }
serde_json = { workspace = true }
lz4_flex = { version = "0.11.1" }
flate2 = { version = "1.0.28" }
local-ip-address = "0.5.6"
udp_sas_async = { version = "0.2.0", features = ["async_std"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }


[[bench]]
name = "sdp_rewrite"
harness = false