[package]
name = "transport-webrtc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { workspace = true }
num_enum = { workspace = true }
indexmap = { workspace = true }
derive_more = { workspace = true, features = ["full"] }
sans-io-runtime = { workspace = true, default-features = false }
prost = { workspace = true }
media-server-utils = { path = "../media_utils" }
media-server-protocol = { path = "../protocol" }
media-server-secure = { path = "../media_secure" }
media-server-core = { path = "../media_core" }
str0m = "0.6"
