[package]
name = "atm0s-media-server-transport-webrtc"
version = "0.3.0-alpha.2"
authors = ["Giang Minh <giang.ndm@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Transport Webrtc Component for Atm0s Media Server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
media-server-utils = { workspace = true }
media-server-protocol = { workspace = true }
media-server-secure = { workspace = true }
media-server-core = { workspace = true }

log = { workspace = true }
num_enum = { workspace = true }
indexmap = { workspace = true }
derive_more = { workspace = true, features = ["full"] }
sans-io-runtime = { workspace = true, default-features = false }
prost = { workspace = true }
str0m = { workspace = true }
