[package]
name = "transport-webrtc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { workspace = true }
num_enum = { workspace = true }
smallmap = { workspace = true }
derive_more = { workspace = true }
sans-io-runtime = { workspace = true, default-features = false }
prost = { workspace = true }
media-server-utils = { path = "../media_utils" }
media-server-protocol = { path = "../protocol" }
media-server-core = { path = "../media_core" }
str0m = { git = "https://github.com/8xff/str0m.git", rev = "24e208c6a12418709a499706fb3eb481ef57a3d2" }
stun-rs = "0.1.8"
