[package]
name = "atm0s-media-server-codecs"
version = "0.1.0"
authors = ["Giang Minh <giang.ndm@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Media Codecs Component for Atm0s Media Server"

[dependencies]
libsoxr = { workspace = true, optional = true }
opusic-sys = { workspace = true, optional = true }

[features]
default = ["opus", "pcma", "resample"]
resample = ["libsoxr"]
opus = ["opusic-sys"]
pcma = ["resample"]
