[package]
name = "media-server-codecs"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
libsoxr = { version = "0.2", optional = true }
opusic-sys = { version = "0.5", optional = true }

[features]
default = ["opus", "pcma", "resample"]
resample = ["libsoxr"]
opus = ["opusic-sys"]
pcma = ["resample"]
